### ISSUE TITLE
Improving agat_sp_manage_functional_annotation.pl 

### ISSUE THREAD

**Issue by nimarafati** [NBISweden/AGAT#103]
Dear Jacques, 

Lucile and I have been discussing about adding a new feature to this script where one can specify species/class to select the blast hits. It can be a parameter in the script so that one specific given species to filter the blast output. In line with this, blast command should be adjusted so that taxonomy information are printed too.

Regards,
Nima

**Comment by Juke34** [comment]
Hi! 
We can get inspiration from this script `agat_sp_load_function_from_protein_align.pl` where we filter by species with ordered priority.
1) How do you want to define the species? Taxid? Latin name?
2) Do you want to define one or several species?

We do not  need to change the blast output. You can keep the blast like it is, the uniprot fasta file used by the script contains species information within the header of each sequence in the `OS` tag. So when looking at the `PE` tag we can also look at the OS tag in the same time

Have you seen with @nylander if he can take care of this task?

Otherwise it will wait until I find the time to look at it.

**Comment by LucileSol** [comment]
Hi!
Thank you for your suggestion!
We would like to be able to define one or several species (both) for your first point we have not discussed it yet, we will.

@nylander can take care of the task, he is going through the different repo and wiki to get to know them better and then will look at this issue.

**Comment by LucileSol** [comment]
Hi!

I noticed something else in that script (that is more a real issue than improvement).

It concerns blast.

case 1 (everything is working fine): 
In the swissprot database I have this protein : 
>sp|P13607|ATNA_DROME Sodium/potassium-transporting ATPase subunit alpha OS=Drosophila melanogaster OX=7227 **GN=Atpalpha** PE=1 SV=3

after blast it matches one of my mRNA:
maker-Bi03_p1mp_000155F-exonerate_protein2genome-gene-6.7-mRNA-3 sp|P13607|ATNA_DROME 69.59 1003 299 2 5 1007 45 1041 0.0 1454

and so I have my annotation in the gff :
Bi03_p1mp_000155F	maker	mRNA	737106	740129	66.73788	+	.	ID=BALIMM00000061851;Parent=BALIMG00000029106;Dbxref=Pfam:PF00689,Pfam:PF13246,Pfam:PF00690,Pfam:PF00122,SUPERFAMILY:SSF81660,SUPERFAMILY:SSF81653,SUPERFAMILY:SSF56784,SUPERFAMILY:SSF81665,Gene3D:G3DSA:1.20.1110.10,Gene3D:G3DSA:2.70.150.10,Gene3D:G3DSA:4.10.6.10,Gene3D:G3DSA:3.40.1110.10,SMART:SM00831,MobiDBLite:mobidb-lite,SFLD:SFLDS00003,Reactome:R-HSA-936837,PANTHER:PTHR24093:SF322,PANTHER:PTHR24093,PRINTS:PR00121,PRINTS:PR00119,InterPro:IPR006068,InterPro:IPR023298,InterPro:IPR023299,InterPro:IPR005775,InterPro:IPR018303,InterPro:IPR008250,InterPro:IPR023214,InterPro:IPR004014,InterPro:IPR001757,ProSitePatterns:PS00154,TIGRFAM:TIGR01106,TIGRFAM:TIGR01494;**Name=atpalpha_iso2**;Ontology_term=GO:0000166,GO:0005391,GO:0005524,GO:0006813,GO:0006814,GO:0016021,GO:0046872;_AED=0.01;_QI=0|-1|0|1|-1|0|1|0|1007;_eAED=0.01;makerName=maker-Bi03_p1mp_000155F-exonerate_protein2genome-gene-6.7-mRNA-3;**product=Sodium/potassium-transporting ATPase subunit alpha;uniprot_id=P13607**

case 2 (problem) : 
In the swissprot database I have this protein : 
>sp|P28774|AT1B_ARTSF Sodium/potassium-transporting ATPase subunit alpha-B OS=Artemia franciscana OX=6661 PE=2 SV=1

after blast it matches one of my mRNA:
maker-Bi03_p1mp_000636F-est_gff_StringTie-gene-1.3-mRNA-1 sp|P28774|AT1B_ARTSF 69.83 1001 295 3 26 1025 10 1004 0.0 1457

and in the gff : 
Bi03_p1mp_000636F	maker	mRNA	93264	98077	1000	-	.	ID=BALIMM00000067022;Parent=BALIMG00000031555;Dbxref=Pfam:PF00122,Pfam:PF00690,Pfam:PF00702,Pfam:PF13246,Pfam:PF00689,SUPERFAMILY:SSF81665,SUPERFAMILY:SSF56784,SUPERFAMILY:SSF81653,SUPERFAMILY:SSF81660,Gene3D:G3DSA:1.20.1110.10,Gene3D:G3DSA:2.70.150.10,Gene3D:G3DSA:4.10.6.10,Gene3D:G3DSA:3.40.1110.10,SMART:SM00831,MobiDBLite:mobidb-lite,SFLD:SFLDS00003,Reactome:R-HSA-936837,PANTHER:PTHR24093,PANTHER:PTHR24093:SF322,PRINTS:PR00121,PRINTS:PR00119,InterPro:IPR001757,InterPro:IPR008250,InterPro:IPR023298,InterPro:IPR023214,InterPro:IPR004014,InterPro:IPR006068,InterPro:IPR018303,InterPro:IPR005775,InterPro:IPR023299,ProSitePatterns:PS00154,TIGRFAM:TIGR01494,TIGRFAM:TIGR01106;Ontology_term=GO:0016021,GO:0000166,GO:0046872,GO:0005391,GO:0005524,GO:0006813,GO:0006814;_AED=0.00;_QI=214|1|1|1|0|0|2|465|1025;_eAED=0.00;makerName=maker-Bi03_p1mp_000636F-est_gff_StringTie-gene-1.3-mRNA-1;**product=hypothetical protein**

This not an hypothetical protein it is a Sodium/potassium-transporting ATPase subunit alpha-B, the problem is in the swissprot fasta file there is no Gene Name (GN=).

There are two possibilities;

1. We change the fasta file of swissprot and force if there is no GN= to add something like for instance : 

>sp|P28774|**AT1B_ARTSF** Sodium/potassium-transporting ATPase subunit alpha-B OS=Artemia franciscana OX=6661 **GN=AT1B_ARTSF** PE=2 SV=1

2. We change the script, something like if there is a blast but no GN then in our case GN=AT1B_ARTSF and then the rest should follow in the gff (like Name=, product= and uniprot_id=) (or maybe not the name but it is not an hypothetical protein!)

I would prefer to change the script, what do you think? @nylander? 

also it is kind of high in my priority now as I have functional parts to run :)

**Comment by nylander** [comment]
Hi all,
sorry for being late on this. I will try to look in to this topic.
Johan
