### ISSUE TITLE
features with more than one parent

### ISSUE THREAD

**Issue by eduardopdev** [NBISweden/AGAT#126]
Hello, I'm trying to convert a GFF file to GTF format and ended up having some problems.
The file i am trying to convert is the Araport11 annotation file from this link:
https://www.arabidopsis.org/download_files/Genes/Araport11_genome_release/Araport11_GFF3_genes_transposons.Mar92021.gff.gz

I used the agat_convert_sp_gff2gtf.pl and it said that the following features were ignored:
* antisense_lncrna
* mirna_primary_transcript
* protein
* pseudogenic_exon
* pseudogenic_trna
* transcript_region
* transposable_element
* transposable_element_gene
* transposon_fragment
* uorf

So i used the --exposed flag to import the .json files to my dir and added the following entries to the .json files as listed below:
"antisense_lncRNA" : "gene"  - features_level2.json
"miRNA_primary_transcript" : "gene" - features_level2.json
"protein" : "1" - features_level3.json
"pseudogenic_exon" : "1" - features_level3.json
"pseudogenic_tRNA" : "gene" - features_level2.json
"transcript_region" : "gene" - features_level2.json
"transposable_element" : "topfeature" - features_level1.json
"transposable_element_gene" : "topfeature" - features_level1.json
"transposon_fragment" : "transposable_element" - features_level3.json
"uorf" : "1" - features_spread.json

the entries with "1" as expected parent value are there because they can have more than 1 feature as parent and even not have a parent at all sometimes (uorf case), i saw that some keys have numbers as values in the level3 and spread have numbers as values so i assumed that they were there for the same reason.

I tried to convert again but now it says that the following features were ignored:
* antisense_lncrna
* gene
* mirna_primary_transcript
* pseudogene
* pseudogenic_trna
* region
* transcript_region
* transposable_element
* transposable_element_gene
* uorf

any ideia of what i might be doing wrong? I looked for features_level in the read the docs page but found nothing but the troubleshooting.

**Comment by Juke34** [comment]
The `1` does not have any meaning in the json file, it is just because we need to put a value.
What you tried to do is close to be correct.
I have some doubt with
 *  `transcript_region` that might be a level1 feature, would it be useful for AGAT to create a gene parent feature? As you wish.
 * `transposon_fragment` must be a level2 feature as you described its parent (transposable_element) as a level1 feature.
 * `uorf` is correct to be in spread feature but must be also definined in one of the 3 levels. You should add "uorf" : "exon" in  features_level3.json.

Then I don't know why AGAT didnn't take in consideration your modifications when you ran it again. Did you hava the modified json files in you current directory? Are the rights correctly set (reading)?

When you run the tool you should see in the log in the terminal which json files are taken into account after the line:
`=> Accessing the feature level json files`

**Comment by eduardopdev** [comment]
The .json files used are the ones in my working directory.
I managed to convert the GFF3 file this time after editing the .json files correctly.
Another problem arose, though. It gives me a lot of warnings saying that it was not able to find the parents for protein and mirna features:

>WARNING level3: No Parent attribute found @ for the feature: Chr1       Araport11	protein	3760	5630	.	+	.	Derives_from "AT1G01010.1"  ; ID "AT1G01010.1-Protein"  ; Name "AT1G01010.1"
>WARNING level2: No Parent attribute found @ for the feature: Chr1       Araport11	miRNA	28635	28655	.	+	.	Alias MIMAT0004260 ; Derives_from "AT1G01046.1"  ; ID "ath-miR838"  ; Name "ath-miR838"  ; Note "microRNA ath-miR838"  ; computational_description "mature miRNA accession:MIMAT0004260"

After the list of warnings, the output says the following:
> 48422 warning messages: WARNING level3: No Parent attribute found 

> 427 warning messages: WARNING level2: No Parent attribute found

> 48873 warning messages: WARNING gff3 reader: Hmmm, be aware that your feature doesn't contain any Parent and locus tag. No worries, we will handle it by considering it as strictly sequential. If you disagree, please provide an ID or a comon tag by locus. 

I undestood that the error occurs because there's no parent attribute for the protein and mirna rows. But i didn't get what it means to treat protein as 'strictly sequencial'. And what does the agat do with the mirna rows. Does it infer the parent from the 'Derives_from" attribute?

**Comment by eduardopdev** [comment]
Another question. The standalone value for the level 1 features must be used for a feature that may or may not have children or only if the feature never has children?

**Comment by Juke34** [comment]
I didn't implement anything special for the 'Derives_from" attribute, it is treated as other "normal" attributes.
 Strictly sequential mean the feature is attached to the last feature from one level up encountered while parsing. 
Depending the formating of your file you could end up with wierd result e.g:

If the last feature Level1 feature met is a `transposable_element` feature and then the parser encounters a `protein` feature (level3 in your case) without information to which feature it should be attached (by ID/Parent relationship or a comon attribute like gene_id) it will be attached to the transposable_element as parent feature.

To better deal with that case I would first use `agat_sq_manage_attributes.pl` to copy the `Derives_from` attribute as `Parent` attribute in those feature types. Then AGAT will look properly for the expected parent even if it is somewhere else in the file.

AGAT removes orphan level1 features except if it is a `standalone` or `topfeature` feature.  So a `standalone` feature may or may not have children it should be handled in the same way by AGAT.


I suggested to put `uorf` as Level3 because you had already put it as a spread feature (features_spread.json). Spread feature are supposed to be able to be split over several locations. Biologicaly when several locations are attached together to create a feature, it implies splicing events. So it means that the feature are over exons. So in your case then I would remove it from features_spread.json and  features_level3.json, and put it in  features_level2.json like that: "uorf" : "gene" - features_spread.json

**Comment by eduardopdev** [comment]
If the value "1" does not mean anything, how does agat finds the parent? just through the parent value?

**Comment by Juke34** [comment]
First by looking at Parent attribute, if absent it is looking for an common attribute like gene_id for GTF files, if absent sequentially by attaching level2 feature to last level1 feature in the file (similarly with level3 feature to the last level2 feature met in the file)

**Comment by eduardopdev** [comment]
I managed to convert the file but i still have some questions. 
The output from the agat_convert_sp_gff2gtf.pl and agat_sp_manage_attributes.pl scripts contains a list of checks where a number of cases of some sort is displayed. Is it possible for me to see the cases? 
By using the -v option with the agat_convert_sp_gff2gtf.pl it did not show the cases, but something interesting happend: 

> convert pseudogene to gene feature

why would it convert a pseudogene feature to a gene?

**Comment by Juke34** [comment]
The best to track what is happening is to use first agat_convert_sp_gxf2gxf.pl to prepare/standardize your file, it will create a log with lot of useful information. Then if you are confident with the file created with this script you can use it for others scripts.

For the pseudogene to a gene I’m not sure. Often you can have l1 feature like pseudogene removed because detected as orphan, and exons of this pseudogene will be used to recreate a  gene feature. It occurs when relationship between the exons and the pseudogene is not set properly in the file.

**Comment by eduardopdev** [comment]
So, In order to see if agat works, I used the GFF3 file from Araport11 from March 9, 2021 and the GTF file from Araport11 from March 17, 2021. I compared both files, and they have the same information.

Then i followed the agat documentation and your recommendations and got a GTF file from the GFF3 Araport11 file, but the output file from the conversion step has new information in it that is not in the original GFF3 file nor in the original GTF.

Could you help me by executing the conversion to check what it's going on?
i can send you the modified features_level files i used through email.

**Comment by Juke34** [comment]
i will not have time to look at it in the next days. But send me all the data I will try to have a look next week.

**Comment by eduardopdev** [comment]
Sorry for the delay. I think it is better to explain why I need agat so you will better understand the problem. I use hisat2 on my pipeline and to use hisat2 i have to build an index extracting the exon and splice_sites coordinates from a gtf file. In order to work with rice i only have a gff3 file and i need a gtf file. To rule out the possibility of the problem being the extraction of exons and splice sites, i tested with the araport11 annotation files. the GFF3 and GTF files available in arabidopsis.org are equivalent but when i convert the GFF3 to GTF the result from the exons and splice sites extraction from the output GTF file is not the same as the extraction from the arabidopsis.org GTF file.

**Comment by Juke34** [comment]
Well I'm not sure that the GTF and GFF file from Arapot has the same information. You said

>  I compared both files, and they have the same information.

What did you do to perform the comparison?

The attribute column for sure does not contain the same information.
I had a quick look at the GTF, and there is plenty of problem, not necessarly harmful (I have to check more deeply) but this is really sad that rare are the DB providing correct files.

e.g. They provide gene_id and transcript_id to region; gene_id used by a region is also used for a gene; gene type feature does have transcript_id, they should not, 3rd column feature type does not respect the GTF specification (e.g. contains snoRNA snRNA transposable_element, etc. They should at least inform somewhere that this is a specific version of GTF. Gene transfert format... since then a region or a transposable_element is a gene? ), etc...

**Comment by eduardopdev** [comment]
well, i did the following:
verified that the 2 files have the same tuples (Chrm, start, end, strand)
then i verified if the set of IDs in both files were the same
and after that i checked if each tuple (chrm, start, end, strand) 
had the same IDs associated with it in both files.

**Comment by Juke34** [comment]
As you can see here #189 TAIR annotaiton, as plenty of official annotation for different species, may contain many issues. AGAT try to fix the issues and will tend to modify the original information. So direct comparison may be difficult to perform, the best is to track modification made by AGAT looking at the log file you got when running  `agat_convert_sp_gxf2gxf.pl`.
