### ISSUE TITLE
merge annotations v slow

### ISSUE THREAD

**Issue by sarjopp** [NBISweden/AGAT#155]
As mentioned in an earlier issue, I am experiencing long run times and no output with agat_sp_merge_annotations.pl. I'm using v0.6.0, installed with conda. I see that there is a v0.7.0 now but I don't find a conda package. The files I'm trying to merge are a Braker2 gff and an EDTA gff. I already had to rename features so that agat would recognize the repeat types, and I think that issue is resolved. Do you have any thoughts?

**Comment by Juke34** [comment]
v0.7.0 is not in conda, but you can install it in the same conda environment in order to already have all dependencies.
Then follow instruction here https://agat.readthedocs.io/en/latest/troubleshooting.html#how-to-use-a-version-of-agat-from-a-specific-branch

replace `git checkout BRANCHE_NAME` by `git checkout v0.7.0` if you want v0.7.0.  If you want the lastest version skip this line.

**Comment by Juke34** [comment]
Could you parse each file independently with `agat_convert_sp_gxf2gxf.pl` to see if there is anyting in the output?

**Comment by sarjopp** [comment]
Thank you, I will try these suggestions and report back!

**Comment by Juke34** [comment]
I updated my comments, so just updating the version should fix your problem.

**Comment by sarjopp** [comment]
Thank you, using the latest version of AGAT fixed my issue!
