### ISSUE TITLE
Use NCBI's nr database with agat_sp_manage_functional_annotation

### ISSUE THREAD

**Issue by sarjopp** [NBISweden/AGAT#156]
How can I add my blast results when I blasted against nr? I did blastp with a taxid list restricting the database to hymenoptera, but the db is based on the whole nr database, NOT on a fasta file that I can feed to agat as -db. How should I tell agat?

**Comment by Juke34** [comment]
Unfortunatly `agat_sp_manage_functional_annotation` has been designed to work with Uniprot only, because we wanted to be able to select cirteria related to "how trustable" is the protein we use to infer the function from. We do that using the Protein Existence (PE) attribute from the fasta header which is not present in NR. 

If we have many demands, we might update the code to manage NR database too.

**Comment by sarjopp** [comment]
Thank you for your reply. I see the logic in sticking with uniprot for reliable annotation at the genome level.

Sara
