### ISSUE TITLE
Filter by minimum exon length

### ISSUE THREAD

**Issue by cassondranewman** [NBISweden/AGAT#213]
Hello, 

Thank you for this outstanding tool!
I ran agat_sp_statistics.pl and got a report on the features of my annotation file. One of the reported features was 'Shortest exon [length]'. I would like to now filter my annotation so that there are no exons less than X bp in length. Is that filtering step possible within AGAT? 

Thanks!

**Comment by Juke34** [comment]
Hi,

It is not a good idea to remove only exons otherwise you might break ORF, phase etc…
You better remove the entire gene/transcript that contains at least one exon under X bp in length. 
to perform that, you must perform a gtf conversion to have gene and transcript ID linked to each feature (exon included). Then you convert the gtf file into tsv. 3rd with a awk command you can compute on the fly to each exon line of your tsv the length and according to your filter choice print the transcript or/and the gene id in a file that will be used as kill list. 4) use the kill list to remove the transcript/gene of you original gff file.

Best

**Comment by cassondranewman** [comment]
That makes perfect sense! Thanks!
