### ISSUE TITLE
merging gff3 files when one is only cds

### ISSUE THREAD

**Issue by jaredbernard** [NBISweden/AGAT#221]
Hi, @Juke34,

My apologies if you've answered this elsewhere. As the title says, I have two gff3 files. One is the output of Maker, and it includes genomic coordinates, strand, and phase. These three things are missing from my other gff3, which is the output of Blast2GO. The only sequence input allowed for Blast2GO, as far as I can tell, is a fasta file, so I used a fasta of my cds. The output gff3 therefore has only the ID of each cds, but I would like to merge the valuable functional annotation from Blast2GO to my structural annotation from Maker.

So the only feature that unites the two files is the ID, which is in the Attributes column. By the way, Blast2GO also replaced the seqids.

Following the guidance you gave on [this thread](https://www.biostars.org/p/9465577/), I tried the following:
```
agat_convert_sp_gxf2gxf.pl --gff filtered_maker.gff3 -c ID -o output1.gff3
agat_convert_sp_gxf2gxf.pl --gff b2g.gff3 -c ID -o output2.gff3
agat_sp_merge_annotations.pl --gff output1.gff3 --gff output2.gff3 -o merged_annotation.gff3
```
As you can probably tell, it didn't work. I ended up with a file double in size, and with about twice the number of genes. Do you have ideas for how to merge such files?

Thanks in advance!

**Comment by Juke34** [comment]
You should not use ‘-c ID’ for the Maker file. This is useful only if the file has only CDS.

**Comment by Juke34** [comment]
If you use AGAT version from conda you will loose functions with agat_sp_merge_annotations.pl. You must update to the version on the ‘merge’ branch or use the approach using tsv file to update the Maker annotation. This can help: https://www.biostars.org/p/9510291/#9511538

**Comment by jaredbernard** [comment]
Thanks, @Juke34! That ought to do the trick. So after converting "CDS" to "centromere" via `sed`, would I use the option `-c` with the command `agat_convert_sp_gff2tsv.pl`, followed by `agat_sq_add_attributes_from_tsv.pl`?

Just like the example in the linked thread, my functional annotations (gff that is only CDS output from Blast2GO) include numerous elements (e.g. ID, description, gene, ontology_term, etc.) and I want them all to be added to the structural annotation output from Maker. So, do I need to use `-c` to list _multiple_ attribute elements, or is there a way to get all the attributes?

**Comment by Juke34** [comment]
If you have changed the CDS into centromere in your case you do not need to use the -c  attribute. This is just used to parse the file properly.   
All attributes will end in a column in a tsv file.
The second script will add all column you have in your input Tsv, so no need to list any attributes. Just filter the tsv file to remove the useless columns and keep only those you need prior to run the script.
btw are your CDS only from single exon genes? If not the trick to Change the CDS into centromere in not the way to go.

**Comment by jaredbernard** [comment]
My CDS are not generally single-exon genes, but instead are mostly multi-exon genes. Do you have another suggestion in that case?

**Comment by Juke34** [comment]
The way described above works in all cases.  
When parsing with AGAT a file with only CDS you need to use what I call a common tag e.g. an attribute that hold the information to link feature to each other. By default AGAT will use gene_id and locus_tag and create a gene and mRNA to each locus_tag or gene_id. If none of them is present AGAT will create a single gene feature and mRNA and link all the CDS to this unique gene, what will be wrong. You can specify the attribute you want to be used as common tag with the -c option but using the ID can be dangerous in one case. 
If you have single exon genes e.g. in prokaryotes then it is fine. As each CDS has a unique ID, AGAT will create a gene and an mRNA to each CDS. When you have multiple exon genes (CDS spread over multiple exons) in some annotations CDS chunks of a single CDS share the same ID while in sone other they will have each a unique ID. It depends tools creating the annotation. If they share the same ID then it is fine, AGAT will create a unique gene/mRNA feature to link all the CDS that have the same ID. But if they have unique ID, AGAT will create a gene/mRNA to each chunk of the CDS, and this is obviously wrong. In that case you must use another attribute to link feature to each other (and if no proper one is available then you are stuck. This type of file should not exist because it has no sense)

**Comment by jaredbernard** [comment]
Thanks so much! That seems to have worked, and is likely the approach that people will need if getting ontology from Blast2GO, because I believe it needs to start with a cds fasta.

```
agat_convert_sp_gxf2gxf.pl --gff maker_annotations.gff3 --merge_loci -o maker_lociMerged.gff3
agat_sp_keep_longest_isoform.pl -gff maker_lociMerged.gff3 [ -o maker_filtered.gff3 ]
agat_convert_sp_gxf2gxf.pl --gff maker_filtered.gff3 -o output1.gff3
sed -i 's/CDS/centromere/g' blast2go-annotation.gff3
agat_convert_sp_gxf2gxf.pl --gff blast2go-annotation.gff3 -c ID -o output2.gff3
agat_convert_sp_gff2tsv.pl --gff output2.gff3 [ -o blast2go.tsv ]
sed -i 's/centromere/CDS/g' blast2go.tsv
more blast2go.tsv
agat_sq_add_attributes_from_tsv.pl --gff output1.gff3 --tsv blast2go_trimmed.tsv [ -o merged_annotation.gff3 ]
more merged_annotation.gff3
```

**Comment by Juke34** [comment]
Thank you for your feedback.
I would say the two first steps are optional (depending if you want to merge overlapping loci and if you want longest isoforms only). The third step is not needed either except to get a log to see what AGAT is doing to sanitize the file.  
The 5th command you do not need to use the option “-c ID” .
I’m worry as you have multi exon genes that you have CDS split in several chunks that share the same ID. CDS chunks are allowed to have  same IDs while other features like the centromere we use here not. So if it the case, when we replace CDS by Centromere and we parse the file with AGAT, the IDs will be modified to be unique. So later when using agat_sq_add_attributes_from_tsv.pl the new IDs will not be recognized. The solution would be to use first the AGAT script to modify IDs to force all CDS IDs to be unique before to run blast2go.
