### ISSUE TITLE
fix_overlapping_genes

### ISSUE THREAD

**Issue by matryoskina** [NBISweden/AGAT#225]
Hi,
I am trying to remove overlapping genes in my gff file (as in attachment). The script "fix_overlapping_genes" seems what I need, but unfortunately it works only with two genes at a time. I have around 3000 overlapping genes, at least from agat_sp_statistics, but when I run "fix_overlapping_genes", only 38 genes were fixed.
s it possible to get an implementation of the script, like all-against-all?

Thanks a lot!
<img width="1427" alt="Screenshot 2022-02-22 at 18 48 50" src="https://user-images.githubusercontent.com/41644747/155189900-28989219-780d-45f7-807a-970833dbee39.png">

**Comment by Juke34** [comment]
Why do you want to remove overlapping genes? What are the criterium to decide if an overlapping gene has to be removed. The script you used is not intended to perform what you want. It just modifies UTR to avoid identical locations between genes or between isoforms for submission purpose because ENA does not accept such type of feature. Do you have only one file/track in which you want to remove overlapping genes? Do you want to remove them or merge them into unique locus?

**Comment by matryoskina** [comment]
But isn't "fix_features_locations_duplicated.pl" that script that does what you describe?
I would like to remove overlapping genes, yes, but already merge them into one gene would be good.

**Comment by Juke34** [comment]
My bad, you are right! 
So yes the script handle all case in one go. If two genes are not merged it is because the criterium are not met:
* they must overlap in same direction 
* the must overlap in their CDS (It is accepted that a gene lives within the UTR of another one, or that UTRs overlaps, so those cases are not merged)

I should anyway update the script to add a parameter to accept to merge attributes when merging the genes
