### ISSUE TITLE
Mismatch between gene and mRNA count after agat_sp_keep_longest_isoform.pl

### ISSUE THREAD

**Issue by sjfleck** [NBISweden/AGAT#244]
I'm using AGAT to remove isoforms from my annotation (and ultimately the protein fasta) for OrthoFinder. My small pipeline:

1. checks the number of genes and mRNA in the original .gff
2. runs agat_sp_keep_longest_isoform.pl
3. checks the number of genes and mRNA in the new .gff
4. runs agat_sp_extract_sequences.pl
5. runs BUSCO on the protein files
6. corrects for duplicated buscos using evigene

For the majority of the assemblies/annotations I've done this for, everything has turned out fine, but a couple are giving me strange results. Before AGAT, I expect the mRNA count to be higher than the gene count. After AGAT, I expect the mRNA and gene counts to be the same. For some reason, with two of the species I'm working with (From other publications, not my own work) are giving me fewer mRNA than genes: Here is a break down from _Prunus avium_ (GCF_002207925.1_PAV_r1.0_genomic.gff):
<img width="358" alt="Screen Shot 2022-04-28 at 3 12 20 PM" src="https://user-images.githubusercontent.com/53409202/165828610-132e33b7-6a8f-4efb-bff7-f48c787e694f.png">

It seems like the "RNA" type is created from "mRNA" that falls under a pseudogene, but this doens't account for the difference in genes vs mRNA.

The other species giving a similar trouble is _Arabidopsis thaliana_ (TAIR10). I had to remove a bunch of entries from their annotation file because it had a lot of position types that were recognized by AGAT and each CDS had 2 parents: a typical one and a protein one. I think having 2 parents was what was causing AGAT to generate 2x the number of genes and mRNA. Even after removing everything and solving the doubling problem, it still has the same issue as _Prunus avium_:
Before AGAT: 28,496 genes & 35,176 mRNA
After AGAT: 28,496 genes & 27,206 mRNA

Any help with this would be greatly appreciated. Thank you

**Comment by Juke34** [comment]
Gene and Pseudogene are level1 feature (30405)
mRNA, lnc_RNA, transcript and RNA are level2 features (30707)
You have a difference of 302 because some genes have probably both mRNA and lnc_RNA. 
RNA are probably build from pseudogenes that do not have children features, and some lnc_RNA are probably pseudogenes (Without CDS agat will build a RNA feature, otherwise it builds a mRNA feature).

To decipher and better understand you should run agat_sp_statistics.pl, you will see what type of level2 features are attached to level1 features.

**Comment by sjfleck** [comment]
Thanks!
