### ISSUE TITLE
gff2gtf generates empty file

### ISSUE THREAD

**Issue by oushujun** [NBISweden/AGAT#263]
I have a gene and a TE annotation both in the gff format and want to merge them together into the gtf format. The gff2gtf converter skipped all TE entries and only output gene entries in the gtf file.

#### General
- AGAT version v0.8.0 
- AGAT installation via Conda
- OS: Linux

#### To Reproduce**
First I used `agat_sp_merge_annotations.pl` to merge two gff files into a single gff ([B73.v5.chr1_1mb.geneTEanno.gff.zip](https://github.com/NBISweden/AGAT/files/8855925/B73.v5.chr1_1mb.geneTEanno.gff.zip)). It was completed without any error.

Then I used `agat_convert_sp_gff2gtf.pl` to convert the merged gff, the run finished without errors, but the output only contains gene entries.

I used `agat_convert_sp_gxf2gxf.pl` to fix the merged gff, as suggested by #63, it didn't change anything.

Thank you so much for your help!

Best,
Shujun

**Comment by Juke34** [comment]
Hi @oushujun, the GTF format allows really few type of features. You must use the `--relax`to avoid to throw away feature types.

**Comment by oushujun** [comment]
Hi Juke,

Thank you so much for your instant response. Adding the `--relax` parameter to `agat_convert_sp_gff2gtf.pl` works perfectly! Thanks again for developing and maintaining AGAT.

Best,
Shujun

**Comment by Juke34** [comment]
They are feature not known by AGAT. If you look at the log or use agat_convert_sp_gxf2gxf.pl you will see that AGAT informs you that it does not know how to deal with them and you need to provide extra info to AGAT via json files in order to be handled properly.

See
* https://agat.readthedocs.io/en/latest/troubleshooting.html#agat-throws-features-out-because-the-feature-type-is-not-yet-taken-into-account
* https://github.com/NBISweden/AGAT/issues/199

Once the json implemented it would be nice to do a PR that this features are ready to be used by AGAT for other Users.
