### ISSUE TITLE
Transform a GTF or GFF file to .tbl

### ISSUE THREAD

**Issue by arturomarin** [NBISweden/AGAT#277]
Hello,

I am in the process of submitting an annotated genome to NCBI. In one part of the process, a .tbl file is required where the annotation is stored. 

https://www.ncbi.nlm.nih.gov/genbank/feature_table/

Is it possible to transform a GTF or GFF file to .tbl with AGAT? I don't find a script in AGAT to do this, Would it be possible to implement this function?

All the best,

**Comment by Juke34** [comment]
Hi, 
This type of conversion is tricky and particular to get a version for submission purpose.  AGAT does not deal with that.

1) You can follow this [NCBI recipe](https://www.ncbi.nlm.nih.gov/genbank/genomes_gff/) to prepare the GFF to be converted in asn.1 with table2asn.  
2) Otherwise it exists a tool called GAG [Genome Annotation Generator - GAG](https://github.com/genomeannotation/GAG) to ease the preparation of your GFF for submission to NCBI.  
3) NCBI and ENA are part of [INSDC](http://www.insdc.org/) and their data are synchronised every day, so everything submitted in one of this DB will also be accessible in the other. So another solution is to submit via ENA. For that purpose we have developed [EMBLmyGFF3](https://github.com/NBISweden/EMBLmyGFF3) that can convert any GFF3 into a valid EMBL flat file that is sumittable via ENA.

**Comment by arturomarin** [comment]
Hi, 

Thank you very much for your quick and helpful response. I'll try the alternatives you suggested.
