### ISSUE TITLE
GFF to GTF conversion: Stop codon not removed in general

### ISSUE THREAD

**Issue by eboileau** [NBISweden/AGAT#314]
**Describe the bug**
On the documentation it is said that the stop codon is removed from the  CDS when converting from GFF to GTF, but it is not in general, unless feature types specifically include `stop_codon`. However most gene annotation GFF files, incl. those from [Ensembl](http://www.ensembl.org), do not.

**General (please complete the following information):**
- AGAT version: agat_1.0.0
- AGAT installation/use: agat_1.0.0--pl5321hdfd78af_0.sif
- OS: SMP Debian 5.10.149-1 (2022-10-17) x86_64 GNU/Linux

**To Reproduce**
I could reproduce that on any GFF file, and this is equally true for genes on both strands. To make things simpler, one can use the GFF test file posted [here](https://agat.readthedocs.io/en/latest/gff_to_gtf.html#the-gff-file-to-convert), and remove the line with the `stop_codon`, _i.e_

```
scaffold625	maker	stop_codon	343031	343033	.	+	.	ID=CLUHART00000008717:stop Parent=CLUHART00000008717
```
then run

```
singularity exec --bind ... agat_1.0.0--pl5321hdfd78af_0.sif agat_convert_sp_gff2gtf.pl --gff example.gff -o example.gtf
```

The resulting GTF file shows, for the last CDS

```
scaffold625     maker   CDS     341964  343033  .       +       2       gene_id "CLUHARG00000005458"; transcript_id "CLUHART00000008717"; ID "CLUHART00000008717:cds"; Parent "CLUHART00000008717";
```

**Expected behavior**
agat_convert_sp_gff2gtf.pl should remove the stop codon from the CDS when converting from GFF to GTF, whether or not the `stop_codon` feature is present or not (or at least mention that it should be present, in such case however this greatly reduces the usefulness...)

Thanks.

**Comment by Juke34** [comment]
Right, originally AGAT uses the information contained within the GFF/GTF file. So if the stop codon is not defined then it cannot really remove it from the CDS when converting from GFF to GTF. When this information is not present you need to work with the FASTA file. It can be cumbersome to always carry the FASTA file when working with AGAT because most of AGAT's tools do not need the FASTA information. But... I there is a script for this task called [agat_sp_add_start_and_stop.pl](https://github.com/NBISweden/AGAT/blob/master/bin/agat_sp_add_start_and_stop.pl) that will use the FASTA information to check the codon and add start/stop accordingly with the codon table in use.

I'm really reluctant to remove or add start/stop by default when doing the GFF to GTF or GTF to GFF conversion because I have seen many dispecrencies where GFF files were not containing stop codon or GTF that were counting stop codon while it is supposed to be the opposite.

**Comment by eboileau** [comment]
Hi @Juke34 thanks for your reply. 

It would be nice to have this as an option, since many gene annotation GFF files do not have the `stop_codon` feature... In all cases, I would suggest to make this clear in the documentation _e.g._ [here](https://agat.readthedocs.io/en/latest/gff_to_gtf.html#test-summary). I was initially mislead, and by chance found out that the stop codon was still present in the GTF.
