### ISSUE TITLE
Failed test:  31

### ISSUE THREAD

**Issue by Tdanis** [NBISweden/AGAT#33]
Hello, so after the command "make test" I took this message
COuld you help me to solve this? Can I proceed the installation or not ?

# Looks like you failed 1 test of 43.
t/scripts_output.t ... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/43 subtests 

Test Summary Report
-------------------
t/scripts_output.t (Wstat: 256 Tests: 43 Failed: 1)
  Failed test:  31
  Non-zero exit status: 1
Files=4, Tests=142, 93 wallclock secs ( 0.06 usr  0.01 sys + 77.56 cusr  9.68 csys = 87.31 CPU)
Result: FAIL
Failed 1/4 test programs. 1/142 subtests failed.
Makefile:1520: recipe for target 'test_dynamic' failed
make: *** [test_dynamic] Error 1

Thank you

**Comment by Juke34** [comment]
Can you run the test in verbose mode?  It will allow to catch the problematic test 
`make test TEST_VERBOSE=1`

You can `make install` anyway it will work. In the worse case one of the 50 scripts will not but I doubt. I guess the test is failing due to a different sorting in the ouput (I probably forgot to sort one hash)

**Comment by Tdanis** [comment]
After "make test TEST_VERBOSE=1" I think it is the same..

# Looks like you failed 1 test of 43.
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/43 subtests 

Test Summary Report
-------------------
t/scripts_output.t (Wstat: 256 Tests: 43 Failed: 1)
  Failed test:  31
  Non-zero exit status: 1
Files=4, Tests=142, 92 wallclock secs ( 0.07 usr  0.01 sys + 76.78 cusr  9.94 csys = 86.80 CPU)
Result: FAIL
Failed 1/4 test programs. 1/142 subtests failed.
Makefile:1520: recipe for target 'test_dynamic' failed
make: *** [test_dynamic] Error 1

Thank you

**Comment by Juke34** [comment]
I thought it would have been more verbose. 
Could you run 
`bin/agat_sp_manage_introns.pl --gff t/scripts_output/1.gff -o result`
and send me the `result` folder? Thank you

**Comment by Tdanis** [comment]
Here you are



Θεόδωρος Δανης
Thodoris Danis

________________________________

**Comment by Juke34** [comment]
It sounds two lines are missing. 
Can you archive it and give me the archive ( result.tar.gz):
`tar cvzf result.tar.gz result/`  
And btw which version are you using?

**Comment by Tdanis** [comment]
[result.tar.gz](https://github.com/NBISweden/AGAT/files/4409637/result.tar.gz)

There is no btw in the path (i am working in hpc) but I have ta latest

**Comment by Juke34** [comment]
Interesting, the problem seems related to R that does not succeed to make a plot (it succeeded the first and do not perform the second). What R version are you using? I'm surprise you didn't get any warning/error related to R when running `bin/agat_sp_manage_introns.pl --gff t/scripts_output/1.gff -o result`.

You may encounter problem in plot part of some scripts then. Installing AGAT with conda may help to avoid this problem.

**Comment by Tdanis** [comment]
the latest again , I am trying conda install now but  ti is very slow, I am trying conda install 5 hours now. I want AGAT scripts in orders to train my Augustus. Are there any scripts that will be affected ? from this error?
