### ISSUE TITLE
Install section: Debian GNU/Linux way

### ISSUE THREAD

**Issue by marcelolaia** [NBISweden/AGAT#38]
Hi! Thank you so much for share this awesome program! Is ti possible to include a subsection "Debian GNU/Linux way" inside Install section? Here is a suggestion that worked for me ( Linux 5.5.0-2-amd64 #1 SMP Debian 5.5.17-1 (2020-04-15) x86_64 GNU/Linux):

Install all dependencies by APT
`apt update && apt upgrade`
`apt install libbio-perl-perl libclone-perl libgraph-perl liblwp-useragent-determined-perl libstatistics-r-perl libjson-perl libcarp-clan-perl libsort-naturally-perl libfile-share-perl libfile-sharedir libfile-sharedir-install-perl`

Clone AGAT
`git clone https://github.com/NBISweden/AGAT.git # Clone AGAT`
`cd AGAT                                         # move into AGAT folder`
`perl Makefile.PL                                # Check all the dependencies*. If it complains for lack of any dependencies, install it using apt. All perl dependencies are in the Debian repositories`
`make                                            # Compile`
`make test                                       # Test`
`sudo make install                               # Install`

Run the `agat_sp_extract_sequences.pl`. For extract `exon`, for example, you could run:

`agat_sp_extract_sequences.pl -f reference_sequence.fa -gff annotation_fasta.gff3 -t exon --split -o output.exons.fa`

I suggest you to include this subsection because I do a lot of search in the net figure out how install anaconda/conda in Debian by apt. I discovered that anaconda/conda isn't needed.

Thank you!

**Comment by Juke34** [comment]
Is it not easier to install conda directly?   
e.g. Miniconda using the linux installer here:  
https://docs.conda.io/en/latest/miniconda.html#linux-installers  
You just have to execute the downloaded file.  

Or using RPM and Debian Repositories  like explained here:  
https://docs.conda.io/projects/conda/en/latest/user-guide/install/rpm-debian.html

If you really don't want to use conda you can install the dependencies either using the packaging tool  of your machine (in your case apt) or cpan as explained in the readme.
I can mention in the readme that it is possible to use packaging tool instead of cpan to install dependencies manually.

**Comment by marcelolaia** [comment]
On 25/04/20 at 05:47, Jacques Dainat wrote:
> 
>    I can mention in the readme that it is possible to use packaging tool
>    instead of cpan to install dependencies manually.

Thank you so much! 

-- 
Laia, ML
https://publons.com/researcher/1755871/
http://orcid.org/0000-0001-6366-4558
