### ISSUE TITLE
Missing double quotes - agat_convert_sp_gff2gtf.pl

### ISSUE THREAD

**Issue by ShenTTT** [NBISweden/AGAT#46]
I used agat_convert_sp_gff2gtf.pl to convert my gff3 file to gtf file but the double quotes of 'gene_id' are missing in the generated gtf file:

`ID "Bany_03723-RA:1"; Parent "Bany_03723-RA"; gene_id Bany_03723; transcript_id "Bany_03723-RA" `

**Comment by Juke34** [comment]
The specification says `Textual attributes should be surrounded by doublequotes.` . They say `should` not  `must`. Everyone is quoting textual values, but when it is not textual it depends groups. Ensembl quote the numerical values. 
I changed the code in order to quote everything even for integer value. 
I also updated the code to put gene_id and transcript_id attributes at first in the attribute list while it was not the case before.
