### ISSUE TITLE
script to detect premature stop codons in CDS

### ISSUE THREAD

**Issue by AMMMachado** [NBISweden/AGAT#58]
Hi Juke,
The agat toolkit is amazing.
I'm using a lot of your scripts to correct and add missing features to a gff3 file of a vertebrate genome. 
Do you have some tool/script to correct/remove non in frame stop condons from gff3 file ? Permature stop codons?

Best Regards

André

**Comment by Juke34** [comment]
Hi,
Happy to hear that you find AGAT useful.
I'm not sure to understand what you are looking for. Either you search to modify the underlying sequence and thus it is an assembly side problem, or you search to modify the structural annotation (redefining the exon-intron structure to avoid the stop codon (you have to take into account the donor/acceptor splicing site)) and it is a gene prediction problem.

AGAT does not have any script to modify the assembly (yet).
There is a script to redefine the ORFs (it will stop the CDS at the first stop met, keeping the longest ORF) see agat_sp_fix_longest_ORF.pl
I could write a script to flag gene with stop codon in frame.

**Comment by AMMMachado** [comment]
Hi,
The assembly, it self is not the target. It's the gff3 file. A script to flag genes with stop codon in frame would be a tremendous help for some projects. I tried to understand this script ( agat_sp_fix_longest_ORF.pl), but I m bit confuse, with the models. How the script work to fix gene models and how to detect putative pseudogene? 
Another question Juke. 
I have removed the incomplete model genes. But this script (agat_sp_filter_incomplete_gene_coding_models.pl) only remove the cds's without both stop and start condon. If the cds have start or stop, the cds is kept. I would like to remove all incomplete cds, without stop, start or both. How can a do that?

Andre

**Comment by Juke34** [comment]
The script extracts the CDS sequence and predict the longest ORF. Then it compares the prediction to the original ORF and classify this prediction according the different cases that can be met: i) Do not overlap; ii)overlap but in a different frame; iii) overlap in the same frame but longer; iv) overlap in the same frame but shorter. The case i) will split the original gene model into 2 gene models. The case iv) is a bit special, it can be the result of an annotation error in the original annotation, it can be a Stop-codon read-through (but `agat_sp_fix_longest_ORF.pl ` do not deal with that), or it can be a pseudogene (shorter than expected. Most likely a case where the original annotation comes from a annotation lift-over). I think I have commented everything referring to pseudogene, because the pseudogene detection was just an experimental feature.
