### ISSUE TITLE
agat_sp_manage_IDs.pl and agat_sp_merge_annotations.pl throws out annotations

### ISSUE THREAD

**Issue by sanyalab** [NBISweden/AGAT#83]
HI Jacques,

I have several gff3 files that look like below

`##gff-version 3`
`##sequence-region Chr01 1 306748077`
`#!Date 2020-10-21`
`#!Type DNA`
`#!Source-version EMBOSS 6.6.0.0`
`Chr01   fuzznuc nucleotide_motif        13777291        13777318        28      -       .       ID=Chr01.1;note=*pat pattern:CGTGGGCGTGGGCGAGGCGGCGCGGAGT
`

I would like to concatenate these and change the "ID" to something else like "Chr01_MOTIF1", "Chr01_MOTIF2" and so on. I have tried both agat_sp_manage_IDs.pl and agat_sp_merge_annotations.pl, but they throw these annotations out, as child features are not provided. I do not have information to create the child features. How do I change the IDs using AGAT?

Thanks
Abhijit

**Comment by Juke34** [comment]
I could write a troubleshooting paragraph in the Readme.
As it is defined in the AGAT's feature json file nucleotide_motif must have a child otherwise it throw it away.
To modify this behaviour you should follow this steps:
```
agat_convert_sp_gxf2gxf.pl --expose
```
then modify the features_level1.json to replace `"nucleotide_motif":"8",` by `"nucleotide_motif":"standalone",`

then you can run `agat_sp_manage_IDs.pl` or `agat_sp_merge_annotations.pl ` normally (the modified json file should be in the same place where you run the script).

**Comment by sanyalab** [comment]
Thank you Jacques. The issue is fixed with the modification you mentioned.
Yes a troubleshooting readme will be nice.

Best Regards
Abhijit
