### ISSUE TITLE
GTF to GFF3

### ISSUE THREAD

**Issue by herlianal12** [NBISweden/AGAT#94]
Hi Juke,
I am using your tool (agat_convert_sp_gxf2gxf.pl) to convert gtf to gff3 file. The gtf contains the Parent ID that I need, but I still do not understand how to change the tool's option to accept XLOC_??? as the ID not creating the new ID for the gene level.
This is the gtf file:
<img width="1428" alt="Screen Shot 2021-01-19 at 7 50 38 am" src="https://user-images.githubusercontent.com/57382343/104975128-b7eff180-5a49-11eb-8fc4-ee76203e2ad2.png">
I got this after running the tool:
<img width="1430" alt="Screen Shot 2021-01-19 at 7 50 07 am" src="https://user-images.githubusercontent.com/57382343/104975249-16b56b00-5a4a-11eb-920f-253955c5b7fa.png">

Is this possible?
<img width="1305" alt="Screen Shot 2021-01-19 at 11 46 25 am" src="https://user-images.githubusercontent.com/57382343/104976112-59784280-5a4c-11eb-8bdc-d434f7ee9540.png">

Cheers,
Lina

**Comment by Juke34** [comment]
1) It is suppose to be like you would like in the last version of AGAT. What AGAT version are you using?
2) Otherwise it might be because it is not possible to do so, e.g. the gene_id is already used by another feature as ID, then the next time it meet a locus that try to use this gene_id as ID, it will create a new ID (with nbis prefix). Check by doing a grep in your file (input and output) of e.g `XLOC_000003`
3) Based on the result of the two first point, it might be an edge case not yet handle by AGAT, that we would have to fix

P.S: It might be useful that you provide the same example as in your picture in a file or in a way we can copy past, like that we could test

**Comment by herlianal12** [comment]
Hi Juke,

I used agat=0.5.1, installing via conda. I have checked and I did not see the gene id XLOC_? being used as ID. Here is the example 
[example.gtf.txt](https://github.com/NBISweden/AGAT/files/5834801/example.gtf.txt). 

Thanks

**Comment by Juke34** [comment]
Ok I have pused a fix. To use it you must install the last version direclty from the repo. Please follow the instruction here: https://github.com/NBISweden/AGAT#use-a-version-of-agat-from-a-specific-branch

**Comment by herlianal12** [comment]
Hi Juke,

Thanks, it works.
